export type BackgroundKeywordRow = {
  top: string;
  direction: "left" | "right";
  duration: number;
  words: string[];
};

export const backgroundKeywordRows: BackgroundKeywordRow[] = [
  {
    top: "1%",
    direction: "left",
    duration: 360,
    words: [
      "ALGORITHMS",
      "TIME COMPLEXITY",
      "SPACE COMPLEXITY",
      "COMPILER",
      "RUNTIME",
      "DATA STRUCTURES",
      "GRAPH THEORY",
      "DYNAMIC PROGRAMMING",
    ],
  },
  {
    top: "10%",
    direction: "right",
    duration: 392,
    words: [
      "NEXT.JS",
      "TYPESCRIPT",
      "REACT",
      "NODE.JS",
      "SERVER ACTIONS",
      "ROUTE HANDLERS",
      "API DESIGN",
      "FULL STACK",
      "WEB PERFORMANCE",
    ],
  },
  {
    top: "19%",
    direction: "left",
    duration: 376,
    words: [
      "DISTRIBUTED SYSTEMS",
      "MICROSERVICES",
      "MESSAGE QUEUE",
      "EVENT DRIVEN",
      "CACHE",
      "REDIS",
      "RABBITMQ",
      "LOAD BALANCING",
      "OBSERVABILITY",
    ],
  },
  {
    top: "28%",
    direction: "right",
    duration: 404,
    words: [
      "SQL",
      "POSTGRESQL",
      "INDEXING",
      "QUERY PLAN",
      "TRANSACTION",
      "LOCKING",
      "CONSISTENCY",
      "REPLICATION",
    ],
  },
  {
    top: "37%",
    direction: "left",
    duration: 368,
    words: [
      "DEVOPS",
      "CI/CD",
      "DOCKER",
      "KUBERNETES",
      "MONITORING",
      "LOGGING",
      "TRACING",
      "SRE",
    ],
  },
  {
    top: "46%",
    direction: "right",
    duration: 398,
    words: [
      "COMPUTER VISION",
      "OPENCV",
      "YOLO",
      "REAL TIME TRACKING",
      "EDGE COMPUTING",
      "MODEL INFERENCE",
      "VIDEO PIPELINE",
      "MULTI OBJECT TRACKING",
    ],
  },
  {
    top: "55%",
    direction: "left",
    duration: 382,
    words: [
      "STATE MACHINE",
      "EMBEDDED CONTROL",
      "MOTION PLANNING",
      "ROBOTICS",
      "SENSOR FUSION",
      "ROS",
      "AUTONOMOUS SYSTEMS",
      "MISSION STRATEGY",
    ],
  },
  {
    top: "64%",
    direction: "right",
    duration: 412,
    words: [
      "SECURITY",
      "JWT",
      "OAUTH",
      "ENCRYPTION",
      "ACCESS CONTROL",
      "RATE LIMITING",
      "FAULT TOLERANCE",
      "AUTONOMOUS ROBOTICS",
    ],
  },
  {
    top: "73%",
    direction: "left",
    duration: 386,
    words: [
      "LATENCY",
      "THROUGHPUT",
      "SCALABILITY",
      "CONCURRENCY",
      "PARALLELISM",
      "FAULT ISOLATION",
      "BACKPRESSURE",
      "CIRCUIT BREAKER",
    ],
  },
  {
    top: "82%",
    direction: "right",
    duration: 420,
    words: [
      "CLOUD NATIVE",
      "INFRASTRUCTURE AS CODE",
      "TERRAFORM",
      "K8S OPERATOR",
      "ROLLING UPDATE",
      "BLUE GREEN",
      "CANARY RELEASE",
      "AUTO SCALING",
    ],
  },
  {
    top: "91%",
    direction: "left",
    duration: 400,
    words: [
      "PROMPT ENGINEERING",
      "LLM AGENTS",
      "EMBEDDINGS",
      "RAG PIPELINE",
      "VECTOR SEARCH",
      "INFERENCE OPTIMIZATION",
      "MODEL SERVING",
      "EDGE AI",
    ],
  },
];
